# Generated by Django 5.2.12 on 2026-03-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Email Verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "An account with this email already exists"},
                max_length=254,
                unique=True,
                verbose_name="Email address",
            ),
        ),
    ]
