services:
  - type: web
    name: savemysnippets-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_SSLMODE
        value: require
      - key: FROM_EMAIL
        sync: false
      - key: CORS_EXTRA_ORIGIN
        sync: false
